// Generated by CoffeeScript 1.6.2
(function() {
  var addAccessor, root;

  addAccessor = function(obj, name, value) {
    return obj[name] = function(_) {
      if (!arguments.length) {
        return obj.properties[name] || value;
      }
      obj.properties[name] = _;
      return obj;
    };
  };

  root = (typeof exports !== "undefined" && exports !== null) || this;

  root.addAccessor = addAccessor;

}).call(this);
